spring.application.name=suppCheck
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://mongodb-service.treasury.svc.cluster.local:27017/suppcheck}
spring.thymeleaf.cache=false

app.version=@project.version@
app.build.timestamp=@maven.build.timestamp@
