apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-external-secret
  namespace: {{ .Values.suppcheck.nameSpace }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: {{ .Values.secretstore.name }}
    kind: ClusterSecretStore
  target:
    name: mongodb-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MONGODB_URI: "mongodb://{{ `{{ .mongoLogin }}` }}:{{ `{{ .mongoSecret }}` }}@{{  `{{ .mongoHost }}`}}:{{ .Values.mongodb.port }}/{{ .Values.mongodb.database }}?authSource=admin"
  data:
    - secretKey: mongoLogin
      remoteRef:
        key: mongoLogin
    - secretKey: mongoSecret
      remoteRef:
        key: mongoSecret
    - secretKey: mongoHost
      remoteRef:
        key: mongoHost