apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.suppcheck.nameSpace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret | quote }}