apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.suppcheck.name}}-service
  namespace: {{ .Values.suppcheck.name}}
spec:
  selector:
    app: {{ .Values.suppcheck.name}}
  ports:
    - protocol: TCP
      port: {{ .Values.suppcheck.service.port}}
      targetPort: {{ .Values.suppcheck.deployment.port}}
  type: {{ .Values.suppcheck.service.type}}