ingress:
 className: nginx
 pathType: ImplementationSpecific

imagePullSecret: ChangeIt

image:
  repository: ghcr.io/biestervictor/suppcheck
  tag: "c4ba20ba8cd65baa3cd93fe5f97b0f7ea794f710"

suppcheck:
  name: suppcheck
  nameSpace: suppcheck
  imagePullSecretDecodingStrategy: Base64
  secrets: my-tls-secret
  tls:
    certKey: tls-crt
    keyKey: tls-key
  volumeClaimTemplates:
    resources:
      requests:
        storage: 1Gi
  deployment:
    port: 8080
  service:
    type: ClusterIP
    port: 3000
    nodePort: 30000
    nodePortEnabled: false
  ingress:
    host: suppcheck-kubitos.biester.vip
    tlsEnabled: true
secretstore:
  name: azure-kv
  tenantId: "71b67176-40e1-4d4e-80fe-9251918425b2"
  vaultUrl: "https://treasurykeyvault.vault.azure.net/"
servicePrincipal:
  name: azure-sp