## MongoDB Express configuration
mongoexpress:
  ingress:
    host: mongoexpress.dev.biester.vip

## general
ingress:
  className: traefik
volume:
  storageClassName: local-path
  storageClassNameEnabled: true

secretstore:
  name: azure-kv
  tenantId: "71b67176-40e1-4d4e-80fe-9251918425b2"
  vaultUrl: "https://treasurykeyvault.vault.azure.net/"
servicePrincipal:
  name: azure-sp
suppcheck:
  imagePullSecretDecodingStrategy: Base64
  ingress:
    host: suppcheck-dev.biester.vip
    tlsEnabled: true